from app.models.datos_metereologicos import DatosMetereologicos
from app.models.frontend_core import (
    CoreAlert,
    CoreAnimal,
    CoreEmployee,
    CoreIncident,
    CoreLactation,
    CoreMachinery,
    CoreTask,
    CoreTreatment,
    CoreZone,
)
from app.models.tools4milk import (
    Alerta,
    AlertaUmbral,
    Animal,
    AsignacionTurno,
    AuditLog,
    BoxRecria,
    Empleado,
    EventoReproductivo,
    EventoSanitario,
    EventoSanitarioRecria,
    Genomica,
    Incidencia,
    Lactacion,
    LecturaCarroMezclador,
    LecturaMeteo,
    LecturaRobotOrdeno,
    Maquinaria,
    Pedido,
    ResumenRelevo,
    TareaCatalogo,
    TareaEjecucion,
    TareaRecurrente,
    Turno,
    TratamientoActivo,
    Zona,
)
from app.models.usuario import Usuario

__all__ = [
    # Legacy core_* (durante migración)
    "CoreAlert",
    "CoreAnimal",
    "CoreEmployee",
    "CoreIncident",
    "CoreLactation",
    "CoreMachinery",
    "CoreTask",
    "CoreTreatment",
    "CoreZone",
    "DatosMetereologicos",
    # Nuevos modelos tools4milk
    "Alerta",
    "AlertaUmbral",
    "Animal",
    "AsignacionTurno",
    "AuditLog",
    "Empleado",
    "EventoSanitario",
    "Incidencia",
    "Lactacion",
    "LecturaMeteo",
    "Maquinaria",
    "Pedido",
    "TareaCatalogo",
    "TareaEjecucion",
    "TareaRecurrente",
    "Turno",
    "TratamientoActivo",
    "Zona",
    # New P1 models
    "BoxRecria",
    "EventoReproductivo",
    "EventoSanitarioRecria",
    "Genomica",
    "LecturaCarroMezclador",
    "LecturaRobotOrdeno",
    "ResumenRelevo",
    # Auth
    "Usuario",
]
